site_name: DnD Stories
repo_url: https://github.com/Jtachan/DnD-Stories

nav:
  - Home: index.md
  - Artefactos:
      - Artefactos: artefactos/index.md
  - Libros:
      - Cocina del monstruo: libros/CdM/index.md
  - Partidas:
      - Hero-Land:
          - Intro: partidas/hero-land/index.md
          - Primera misión: partidas/hero-land/cap1.md

theme:
  name: material
  # color scheme configuration
  # changing between light and dark mode is already enabled
  # available primary colors: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.tooltips
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - search.suggest
    - search.highlight
    - toc.follow

markdown_extensions:
  # some selected markdown extensions
  # feel free to add more
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - toc:
      permalink: true
plugins:
  - search
